import { Inter } from "next/font/google";
import "./globals.css";

import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "hablu programmer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <ul className="flex">
        <li className="m-3"><Link href={"/"}>Home</Link></li>
        <li className="m-3"><Link href={"/about"}>about</Link></li>
        <li className="m-3"><Link href={"/class"}>class</Link></li>
        <li className="m-3"><Link href={"/login"}>login</Link></li>
      </ul>
      </body>
    </html>
  );
}
